# Generated by Django 4.1.7 on 2023-04-21 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delhi_lat_delhi_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delhi',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
