# Generated by Django 4.1.7 on 2023-04-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_delhi_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delhi',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='delhi',
            name='lon',
        ),
    ]
