# Generated by Django 4.1.7 on 2023-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delhi_desc_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delhi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
